In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]],[[7,8,9],[9,8,7]]])
print(a.shape,a.ndim)
print(b.shape,b.ndim)
print(c.shape,c.ndim)

(4,) 1
(2, 3) 2
(3, 2, 3) 3


In [2]:
np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [3]:
rm=np.random.choice(np.arange(1, 21), size=(3, 3))
rm

array([[12, 17,  7],
       [ 6, 12,  4],
       [18, 10, 18]])

In [4]:
print(rm[1,:])

[ 6 12  4]


In [5]:
print(rm[:,1])


[17 12 10]


In [6]:
subarray = rm[0:2, 1:4]
subarray


array([[17,  7],
       [12,  4]])

In [7]:
rm[rm%2==0]=-1
rm

array([[-1, 17,  7],
       [-1, -1, -1],
       [-1, -1, -1]])

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [9]:
m=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
m.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])